NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200 
NDefines.NDiplomacy.DAYS_TO_DECLARE_WAR = 4
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.LAND_FORCELIMIT_EXTRA_COST_FACTOR = 3
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 24