NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200 
NDefines.NDiplomacy.DAYS_TO_DECLARE_WAR = 3
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.LAND_FORCELIMIT_EXTRA_COST_FACTOR = 2
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 24
NDefines.NMilitary.BACK_LINE_MORALE_DAMAGE_TAKEN_MODIFIER = 0.0
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 1